[build]
  publish = "."
  command = "# 如需構建命令請取消註釋並填寫"

[dev]
  framework = "# static"
  publish = "."
  port = 8888
  targetPort = 8888
  autoLaunch = true
  
# 啟用表單處理功能
[build.processing.html]
  pretty_urls = true

# 設置HTTP標頭以提高安全性
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; img-src 'self' data:; style-src 'self' 'unsafe-inline'; script-src 'self' 'unsafe-inline'"

# 設置重定向規則
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false
  # 移除了 admin 角色限制條件

# 環境變量設置
[context.production.environment]
  NETLIFY_SITE_NAME = "yongmao-elastomer"
